### ISSUE TITLE
Add animations to the site

### ISSUE THREAD

**Issue by LeonardoZanotti** [LeonardoZanotti/hacktoberfest-repositories#3]
I think the imagens and links will be coolest if it has some animations on hover, or without hover too. Be creative, padding, color, position, flip, shadow, shake, etc etc css animations.

**Comment by mihmilicio** [comment]
I'd love to! Can you assign this to me?

**Comment by caseymhunt** [comment]
In #4 I've added a very subtle transition on hover and focus in addition to styling them as cards so it's a bit easier to visually parse what's on the page. 

Additionally I've modified the DOM to have more semantically meaningful elements.

**Comment by LeonardoZanotti** [comment]
> I'd love to! Can you assign this to me?

Sure, anyone can contribute

**Comment by LeonardoZanotti** [comment]
Thanks all, the website is awesome
