### ISSUE TITLE
Fix the "Its Hacktoberfest!!!" animation in Chrome/Opera/Edge

### ISSUE THREAD

**Issue by LeonardoZanotti** [LeonardoZanotti/hacktoberfest-repositories#6]
In Firefox, the animation of the title "Its Hacktoberfest!!!" looks like this:
![Screenshot at 2020-10-07 11-03-20](https://user-images.githubusercontent.com/61800222/95344858-753a4d00-0890-11eb-83eb-e5e757ace6d6.png)

But in Chrome/Opera/Edge and others navigators, the animation becomes this:
![Screenshot at 2020-10-07 11-03-08](https://user-images.githubusercontent.com/61800222/95344722-520f9d80-0890-11eb-88c5-90d228ac331d.png)

Is needed to adjust the colored borders in the animation

**Comment by indremak** [comment]
I could try to fix it

**Comment by kartikagarwal9** [comment]
I will try it too
